### ISSUE TITLE
Module '"vue3-promise-dialog"' has no exported member 'DialogWrapper'

### ISSUE THREAD

**Issue by jakenuts** [rlemaigre/vue3-promise-dialog#1]
Installed vue3-promise-dialog in existing webpack/typescript vue app, PromiseDialog is imported fine but there doesn't appear to be a DialogWrapper component exported (at least as far as typescript knows).

import { DialogWrapper } from 'vue3-promise-dialog';

**Comment by rlemaigre** [comment]
Oh sorry. I only tested the project on Stackblitz and no error was reported.

I use Vite library mode to build this lib. Unfortunately, it doesn't generate Typescript definition files by itself. I fiddled a lot with this but couldn't find a proper solution. I'll take a look at it again.

Any help on this is appreciated.

**Comment by jakenuts** [comment]
No worries, also noticed I have strict typescript checking on so I'm undoubtedly more "errors" than I should. Will see if I can resolve it.

**Comment by rlemaigre** [comment]
I'll take a look at this plugin and see if it solves the problem : https://github.com/qmhc/vite-plugin-dts

**Comment by rlemaigre** [comment]
It should be fine now.
