### ISSUE TITLE
Cannot find name '$close' vs-code

### ISSUE THREAD

**Issue by lomonoshka** [rlemaigre/vue3-promise-dialog#3]
Everything works great, but vs-code tells me that it can't find function $close. From where should I find it's declaration? Or maybe there is some workaround to just hide the error?

**Comment by rlemaigre** [comment]
Hello, it's declared [here](https://github.com/rlemaigre/vue3-promise-dialog/blob/8ede875c4ad2fc48d279ec97d01d857d50e8f98a/lib/ts/lib.ts#L63). When you install the plugin, it creates that global function and makes it available in all components. I'm not sure that VSCode can pick that up :-/

**Comment by rlemaigre** [comment]
Actually $close could be a plain JS function rather than a member function of components introduced by a plugin...since you have to pass this anyway...I don't know why I did it this way. I must look into this.

**Comment by smitt04** [comment]
It would be nice as a function that could be imported from the library, but something like this will get you by if placed in a `.d.ts` file

```ts
declare module "@vue/runtime-core" {
  interface ComponentCustomProperties {
    $close: (comp?: Component, fallback?: any) => void;
  }
}
```

**Comment by rlemaigre** [comment]
$close has been deprecated, please use closeDialog now, see docs
