### ISSUE TITLE
using vue3-promise-dialog with <script setup>

### ISSUE THREAD

**Issue by meljturner** [rlemaigre/vue3-promise-dialog#8]
If using <script setup> it is necessary to expose the returnValue function in the following way. (It took me a while to figure this out; perhaps the README can be updated)

defineExpose({
  returnValue: () => { return true },
});

**Comment by brunok** [comment]
Thanks. That save ME hours...

**Comment by rlemaigre** [comment]
Sorry about this. I updated the README so that other people can benefit from this.
